### ISSUE TITLE
🇺🇸 Don't suggest this! | 🇧🇷 Não sugira isso!

### ISSUE THREAD

**Issue by WhatsAppAuthenticator** [WhatsAppAuthenticator/WhatsAppAuthenticator#1]
# English
### The suggestions described here have already been suggested by users and approved/disapproved by our team.

- [x] Suggestion approved
- [ ] Suggestion disapproved

> - All disapproved suggestions will have reason, so avoid unnecessary questions on the support server!

# Português (Brasil)
### As sugestões aqui descritas já foram sugeridas por usuários e aprovadas/reprovadas por nossa equipe.

- [x] Sugestão aprovada
- [ ] Sugestão reprovada

> - Todas as sugestões reprovadas terão um motivo, portanto, evite perguntas desnecessárias no servidor de suporte!

**Comment by wesleifurtado** [comment]
- [ ] Suggestion Status

- **Suggestion sent | Sugestão enviada** Adicionar a função de remover um cargo quando completar a verificação.
- **Suggestion sent in | Sugestão enviada em:** Community & Support

`Staff Team Response: We will not approve it at this time, as we do not see reasonable reasons ​​to add this funcion in WhatsApp Authenticator. Order for to perform a system check on your server, we recommend that go to: https://docs.whatsappauthbot.com/support/permissions`.

**Comment by wesleifurtado** [comment]
- [x] Suggestion Status

- **Suggestion sent | Sugestão enviada:** Adicionar a função de limpar no botão esquerdo ao de 'OK' [Limpando todo número colocado na mensagem]
- **Suggestion sent in | Sugestão enviada em:** Community & Support

~~Staff Team Response: We take into account and will soon be implemented in WhatsApp Authenticator.~~
`Staff Team Response [Edit in: 10/07/21]: Suggestion implemented!`

**Comment by wesleifurtado** [comment]
- [ ] Suggestion Status

- **Suggestion sent | Sugestão enviada:** Ter um sistema que apaga as mensagens que o usuário enviar no canal de verify/registro
- **Suggestion sent in | Sugestão enviada em:** Community & Support

`Staff Team Response: This system will not exist, as we will change the way the user verify their respective accounts on the server. Please wait as there will be updates in the future.`

**Comment by WhatsAppAuthenticator** [comment]
test

**Comment by wesleifurtado** [comment]
- [ ] Suggestion Status

- **Suggestion sent | Sugestão enviada:** Permanent Premium Plan
- **Suggestion sent in | Sugestão enviada em:** Community & Support

`Staff Team Response: There is the possibility for the user to obtain the Premium for free just by voting through top.gg, click here for more information. There will be no permanent Premium plan, except in specific cases that will not be mentioned for internal reasons.`
