### ISSUE TITLE
Suggestion 1

### ISSUE THREAD

**Issue by ravenastar-js** [WhatsAppAuthenticator/WhatsAppAuthenticator#8]
Sugestão de implementação no bot WhatsAppAuthenticator, quando o usuário solicitar "Exclusão de dados da conta" ter um sistema que informe que determinado usuário solicitou a exclusão de dados da conta, pode até fazer um canal de anuncio em vez de ter que fazer um sistema para isso...

Exemplo:
> Os dados de `Tigmo#0001 - 441020013046923274` foram removidos do banco dedados do bot `WhatsApp Authenticator#0418`, pois o mesmo solicitou a remoção.

【NOTE】Será uma mão na roda, já que o usuário pode fazer isso para registrar em um servidor, enviar a solicitação de remoção e ainda permanecer no servidor o qual registrou antes da remoção dos dados...

**Comment by wesleifurtado** [comment]
**Thanks!** Your suggestion has been implemented on the Support Server.
